name: Build chip-tool for arm_cortex-a7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        sdk_version: ["25.12.0"]
        target: ["imx/cortexa7"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build with OpenWrt SDK
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: arm_cortex-a7
          TARGET: ${{ matrix.target }}
          SDK: ${{ matrix.sdk_version }}
          PACKAGES: chip-tool             # ← только это обязательно
          # FEEDNAME: custom              # ← можно убрать, default action тоже работает
          # NO_DEFAULT_FEEDS: true        # ← только если хочешь отключить стандартные feeds (редко нужно)

      - name: Upload artifacts (ipk + logs)
        uses: actions/upload-artifact@v4
        with:
          name: chip-tool-${{ matrix.sdk_version }}-${{ matrix.target }}
          path: |
            bin/packages/**/*.ipk
            logs/**/*
          if-no-files-found: warn
