name: Build chip-tool for arm_cortex-a7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        sdk_version: ["25.12.0"]
        target: ["imx/cortexa7"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build package with OpenWrt SDK
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: arm_cortex-a7
          TARGET: ${{ matrix.target }}
          SDK: ${{ matrix.sdk_version }}
          PACKAGES: chip-tool                  # ← это работает
          FEEDNAME: custom                     # ← переименуй feed, чтобы не было конфликта с "action"
          # FEED_DIR: .                        # по умолчанию корень — ок
          # EXTRA_FEEDS: ...                   # если нужны внешние feeds
          # NO_DEFAULT_FEEDS: true             # если хочешь отключить стандартные feeds SDK (редко)

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: chip-tool-$$   {{ matrix.sdk_version }}-   $${{ matrix.target }}
          path: bin/packages/*/*/chip-tool/*.ipk
          if-no-files-found: warn
